package br.com.saveeditor.brasfoot.domain.enums;

public enum Country {
    AFEGANISTAO(0, "AFG", "Afeganistão", Continent.ASIA, 14),
    AFRICA_DO_SUL(1, "AFS", "Africa do Sul", Continent.AFRICA, 16),
    ALBANIA(2, "ALB", "Albânia", Continent.EUROPE, 15),
    ALEMANHA(3, "ALE", "Alemanha", Continent.EUROPE, 20),
    ANDORRA(4, "AND", "Andorra", Continent.EUROPE, 13),
    ANGOLA(5, "AGO", "Angola", Continent.AFRICA, 15),
    ANGUILLA(6, "AIA", "Anguilla", Continent.NORTH_AMERICA, 12),
    ANTIGUA(7, "ATG", "Antigua", Continent.NORTH_AMERICA, 13),
    CURACAO(8, "CUR", "Curaçao", Continent.NORTH_AMERICA, 13),
    ARABIA_SAUDITA(9, "ARS", "Arábia Saudita", Continent.ASIA, 17),
    ARGELIA(10, "ALG", "Argélia", Continent.AFRICA, 18),
    ARGENTINA(11, "ARG", "Argentina", Continent.SOUTH_AMERICA, 20),
    ARMENIA(12, "ARM", "Armênia", Continent.EUROPE, 14),
    ARUBA(13, "ARU", "Aruba", Continent.NORTH_AMERICA, 12),
    AUSTRALIA(14, "AUS", "Austrália", Continent.ASIA, 17),
    AUSTRIA(15, "AUT", "Áustria", Continent.EUROPE, 17),
    AZERBAIJAO(16, "AZE", "Azerbaijão", Continent.EUROPE, 14),
    BAHAMAS(17, "BAH", "Bahamas", Continent.NORTH_AMERICA, 13),
    BAHRAIN(18, "BHR", "Bahrain", Continent.ASIA, 14),
    BANGLADESH(19, "BAN", "Bangladesh", Continent.ASIA, 13),
    BARBADOS(20, "BAR", "Barbados", Continent.NORTH_AMERICA, 13),
    BELGICA(21, "BEL", "Bélgica", Continent.EUROPE, 19),
    BELIZE(22, "BLZ", "Belize", Continent.NORTH_AMERICA, 13),
    BENIN(23, "BEN", "Benin", Continent.AFRICA, 14),
    BERMUDAS(24, "BER", "Bermudas", Continent.NORTH_AMERICA, 13),
    BELARUS(25, "BIE", "Belarus", Continent.EUROPE, 15),
    BOLIVIA(26, "BOL", "Bolivia", Continent.SOUTH_AMERICA, 16),
    BOSNIA(27, "BOS", "Bósnia", Continent.EUROPE, 16),
    BOTSUANA(28, "BOT", "Botsuana", Continent.AFRICA, 13),
    BRASIL(29, "BRA", "Brasil", Continent.SOUTH_AMERICA, 20),
    BRUNEI(30, "BRU", "Brunei", Continent.ASIA, 12),
    BULGARIA(31, "BUL", "Bulgária", Continent.EUROPE, 16),
    BURKINA_FASO(32, "BKF", "Burkina Faso", Continent.AFRICA, 15),
    BURUNDI(33, "BUR", "Burundi", Continent.AFRICA, 13),
    BUTAO(34, "BUT", "Butão", Continent.ASIA, 12),
    CABO_VERDE(35, "CAV", "Cabo Verde", Continent.AFRICA, 15),
    CAMAROES(36, "CAM", "Camarões", Continent.AFRICA, 17),
    CAMBOJA(37, "CMJ", "Camboja", Continent.ASIA, 13),
    CANADA(38, "CAN", "Canadá", Continent.NORTH_AMERICA, 15),
    CATAR(39, "CAT", "Catar", Continent.ASIA, 16),
    CAZAQUISTAO(40, "CAZ", "Cazaquistão", Continent.EUROPE, 14),
    CHADE(41, "CHA", "Chade", Continent.AFRICA, 12),
    CHILE(42, "CHI", "Chile", Continent.SOUTH_AMERICA, 18),
    CHINA(43, "CHN", "China", Continent.ASIA, 17),
    CHIPRE(44, "CPR", "Chipre", Continent.EUROPE, 15),
    TIMOR_LESTE(45, "TML", "Timor-Leste", Continent.ASIA, 12),
    COLOMBIA(46, "COL", "Colômbia", Continent.SOUTH_AMERICA, 18),
    CONGO(47, "CNG", "Congo", Continent.AFRICA, 16),
    COREIA_DO_NORTE(48, "CRN", "Coreia do Norte", Continent.ASIA, 14),
    COREIA_DO_SUL(49, "CRS", "Coreia do Sul", Continent.ASIA, 17),
    COSTA_DO_MARFIM(50, "COM", "Costa do Marfim", Continent.AFRICA, 17),
    COSTA_RICA(51, "CSR", "Costa Rica", Continent.NORTH_AMERICA, 17),
    CROACIA(52, "CRO", "Croácia", Continent.EUROPE, 19),
    CUBA(53, "CUB", "Cuba", Continent.NORTH_AMERICA, 14),
    DINAMARCA(54, "DIN", "Dinamarca", Continent.EUROPE, 18),
    DJIBUTI(55, "DJI", "Djibuti", Continent.AFRICA, 12),
    DOMINICA(56, "DOM", "Dominica", Continent.NORTH_AMERICA, 13),
    EGITO(57, "EGI", "Egito", Continent.AFRICA, 17),
    EL_SALVADOR(58, "ELS", "El Salvador", Continent.NORTH_AMERICA, 16),
    EMIRADOS_ARABES(59, "EMI", "Emirados Árabes", Continent.ASIA, 17),
    EQUADOR(60, "EQU", "Equador", Continent.SOUTH_AMERICA, 16),
    ERITREIA(61, "ERI", "Eritréia", Continent.AFRICA, 12),
    ESCOCIA(62, "ESC", "Escócia", Continent.EUROPE, 16),
    ESLOVAQUIA(63, "ELQ", "Eslováquia", Continent.EUROPE, 17),
    ESLOVENIA(64, "ESV", "Eslovênia", Continent.EUROPE, 16),
    ESPANHA(65, "ESP", "Espanha", Continent.EUROPE, 20),
    ESTONIA(66, "EST", "Estônia", Continent.EUROPE, 15),
    ETIOPIA(67, "ETI", "Etiópia", Continent.AFRICA, 13),
    EUA(68, "EUA", "EUA", Continent.NORTH_AMERICA, 18),
    FIJI(69, "FIJ", "Fiji", Continent.OCEANIA, 12),
    FINLANDIA(70, "FIN", "Finlândia", Continent.EUROPE, 16),
    FILIPINAS(71, "FIL", "Filipinas", Continent.ASIA, 14),
    FRANCA(72, "FRA", "França", Continent.EUROPE, 20),
    GABAO(73, "GAB", "Gabão", Continent.AFRICA, 15),
    GAMBIA(74, "GAM", "Gâmbia", Continent.AFRICA, 13),
    GANA(75, "GAN", "Gana", Continent.AFRICA, 17),
    GEORGIA(76, "GEO", "Georgia", Continent.EUROPE, 14),
    GRANADA(77, "GRA", "Granada", Continent.NORTH_AMERICA, 13),
    GRECIA(78, "GRE", "Grécia", Continent.EUROPE, 16),
    GUATEMALA(79, "GUA", "Guatemala", Continent.NORTH_AMERICA, 14),
    GUIANA(80, "GUN", "Guiana", Continent.NORTH_AMERICA, 13),
    GUINE(81, "GUI", "Guiné", Continent.AFRICA, 16),
    GUINE_BISSAU(82, "GNB", "Guiné-Bissau", Continent.AFRICA, 14),
    GUINE_EQUATORIAL(83, "GNE", "Guiné Equatorial", Continent.AFRICA, 13),
    HAITI(84, "HAI", "Haiti", Continent.NORTH_AMERICA, 14),
    HOLANDA(85, "HOL", "Holanda", Continent.EUROPE, 19),
    HONDURAS(86, "HON", "Honduras", Continent.NORTH_AMERICA, 16),
    HONG_KONG(87, "HKG", "Hong Kong", Continent.ASIA, 14),
    HUNGRIA(88, "HUN", "Hungria", Continent.EUROPE, 17),
    IEMEN(89, "IEM", "Iêmen", Continent.ASIA, 13),
    ILHAS_CAYMAN(90, "ICA", "Ilhas Cayman", Continent.NORTH_AMERICA, 12),
    ILHAS_COOK(91, "ICO", "Ilhas Cook", Continent.OCEANIA, 12),
    ILHAS_FAROE(92, "IFA", "Ilhas Faroe", Continent.EUROPE, 14),
    ILHAS_SALOMAO(93, "ISA", "Ilhas Salomão", Continent.OCEANIA, 14),
    ILHAS_VIRGENS_BRITANICAS(94, "IVB", "Ilhas Virgens Britânicas", Continent.NORTH_AMERICA, 12),
    INDIA(95, "IND", "Índia", Continent.ASIA, 14),
    INDONESIA(96, "IDO", "Indonésia", Continent.ASIA, 14),
    INGLATERRA(97, "ING", "Inglaterra", Continent.EUROPE, 20),
    IRA(98, "IRA", "Irã", Continent.ASIA, 18),
    IRAQUE(99, "IRQ", "Iraque", Continent.ASIA, 16),
    IRLANDA(100, "IRL", "Irlanda", Continent.EUROPE, 16),
    IRLANDA_DO_NORTE(101, "IRN", "Irlanda do Norte", Continent.EUROPE, 17),
    ISLANDIA(102, "ISL", "Islândia", Continent.EUROPE, 16),
    ISRAEL(103, "ISR", "Israel", Continent.EUROPE, 12),
    ITALIA(104, "ITA", "Itália", Continent.EUROPE, 20),
    MONTENEGRO(105, "MON", "Montenegro", Continent.EUROPE, 16),
    JAMAICA(106, "JAM", "Jamaica", Continent.NORTH_AMERICA, 16),
    JAPAO(107, "JAP", "Japão", Continent.ASIA, 18),
    JORDANIA(108, "JOR", "Jordânia", Continent.ASIA, 15),
    QUENIA(109, "QUE", "Quênia", Continent.AFRICA, 14),
    KOSOVO(110, "KOS", "Kosovo", Continent.EUROPE, 14),
    KUWAIT(111, "KUW", "Kuwait", Continent.ASIA, 14),
    LAOS(112, "LAO", "Laos", Continent.ASIA, 13),
    LESOTO(113, "LES", "Lesoto", Continent.AFRICA, 13),
    LETONIA(114, "LET", "Letônia", Continent.EUROPE, 15),
    LIBANO(115, "LBN", "Libano", Continent.ASIA, 15),
    LIBIA(116, "LIB", "Líbia", Continent.AFRICA, 15),
    LIBERIA(117, "LRI", "Libéria", Continent.AFRICA, 13),
    LIECHTENSTEIN(118, "LIE", "Liechtenstein", Continent.EUROPE, 13),
    LITUANIA(119, "LIT", "Lituânia", Continent.EUROPE, 15),
    LUXEMBURGO(120, "LUX", "Luxemburgo", Continent.EUROPE, 13),
    MACAU(121, "MAC", "Macau", Continent.ASIA, 13),
    MACEDONIA_DO_NORTE(122, "MCD", "Macedônia do Norte", Continent.EUROPE, 14),
    MADAGASCAR(123, "MAD", "Madagascar", Continent.AFRICA, 13),
    MALASIA(124, "MAL", "Malásia", Continent.ASIA, 13),
    MALAWI(125, "MWI", "Malawi", Continent.AFRICA, 14),
    MALDIVAS(126, "MLD", "Maldivas", Continent.ASIA, 13),
    MALI(127, "MLI", "Mali", Continent.AFRICA, 16),
    MALTA(128, "MTA", "Malta", Continent.EUROPE, 13),
    MARROCOS(129, "MAR", "Marrocos", Continent.AFRICA, 17),
    MAURITANIA(130, "MAU", "Mauritânia", Continent.AFRICA, 13),
    MEXICO(131, "MEX", "México", Continent.NORTH_AMERICA, 19),
    MIANMAR(132, "MIA", "Mianmar", Continent.ASIA, 13),
    MOCAMBIQUE(133, "MOC", "Moçambique", Continent.AFRICA, 14),
    MOLDAVIA(134, "MOL", "Moldávia", Continent.EUROPE, 14),
    MONACO(135, "MNC", "Mônaco", null, 12),
    MONGOLIA(136, "MGL", "Mongolia", Continent.ASIA, 13),
    NAMIBIA(137, "NAM", "Namíbia", Continent.AFRICA, 14),
    NEPAL(138, "NEP", "Nepal", Continent.ASIA, 13),
    NICARAGUA(139, "NIC", "Nicaragua", Continent.NORTH_AMERICA, 14),
    NIGER(140, "NIR", "Níger", Continent.AFRICA, 14),
    NIGERIA(141, "NIG", "Nigéria", Continent.AFRICA, 18),
    NORUEGA(142, "NOR", "Noruega", Continent.EUROPE, 17),
    NOVA_ZELANDIA(143, "NOZ", "Nova Zelândia", Continent.OCEANIA, 16),
    OMA(144, "OMA", "Omã", Continent.ASIA, 15),
    PAIS_DE_GALES(145, "PGA", "País de Gales", Continent.EUROPE, 17),
    PALESTINA(146, "PAL", "Palestina", Continent.ASIA, 15),
    PANAMA(147, "PAN", "Panamá", Continent.NORTH_AMERICA, 16),
    PAPUA_NOVA_GUINE(148, "PNG", "Papua Nova Guiné", Continent.OCEANIA, 13),
    PAQUISTAO(149, "PAQ", "Paquistão", Continent.ASIA, 13),
    PARAGUAI(150, "PAR", "Paraguai", Continent.SOUTH_AMERICA, 17),
    PERU(151, "PER", "Peru", Continent.SOUTH_AMERICA, 17),
    POLONIA(152, "POL", "Polônia", Continent.EUROPE, 18),
    PORTO_RICO(153, "PRI", "Porto Rico", Continent.NORTH_AMERICA, 13),
    PORTUGAL(154, "POR", "Portugal", Continent.EUROPE, 19),
    QUIRGUISTAO(155, "QUI", "Quirguistão", Continent.ASIA, 15),
    REP_CENTRO_AFRICANA(156, "RCA", "Rep. Centro-Africana", Continent.AFRICA, 13),
    REP_DEM_CONGO(157, "RDG", "Rep. Dem. Congo", Continent.AFRICA, 16),
    REP_DOMINICANA(158, "RDO", "Rep. Dominicana", Continent.NORTH_AMERICA, 13),
    REPUBLICA_TCHECA(159, "RTC", "República Tcheca", Continent.EUROPE, 17),
    ROMENIA(160, "ROM", "Romênia", Continent.EUROPE, 17),
    RUANDA(161, "RUA", "Ruanda", Continent.AFRICA, 13),
    RUSSIA(162, "RUS", "Rússia", Continent.EUROPE, 18),
    SAMOA(163, "SAM", "Samoa", Continent.OCEANIA, 12),
    SAN_MARINO(164, "SAN", "San Marino", Continent.EUROPE, 12),
    SANTA_LUCIA(165, "STL", "Santa Lúcia", Continent.NORTH_AMERICA, 13),
    SAO_CRISTOVAO_E_NEVES(166, "SCN", "São Cristovão e Neves", Continent.NORTH_AMERICA, 14),
    SAO_TOME_E_PRINCIPE(167, "STP", "São Tomé e Príncipe", Continent.AFRICA, 12),
    SAO_VICENTE_E_GRANADINAS(168, "SVG", "São Vicente e Granadinas", Continent.NORTH_AMERICA, 13),
    SENEGAL(169, "SEN", "Senegal", Continent.AFRICA, 17),
    SERRA_LEOA(170, "SLE", "Serra Leoa", Continent.AFRICA, 14),
    SERVIA(171, "SER", "Sérvia", Continent.EUROPE, 17),
    SEYCHELLES(172, "SEY", "Seychelles", Continent.AFRICA, 12),
    SINGAPURA(173, "SIN", "Singapura", Continent.ASIA, 13),
    SIRIA(174, "SIR", "Síria", Continent.ASIA, 16),
    SOMALIA(175, "SOM", "Somália", Continent.AFRICA, 12),
    SRI_LANKA(176, "SRI", "Sri Lanka", Continent.ASIA, 12),
    ESSUATINI(177, "ESS", "Essuatíni", Continent.AFRICA, 13),
    SUDAO(178, "SUD", "Sudão", Continent.AFRICA, 13),
    SUECIA(179, "SUE", "Suécia", Continent.EUROPE, 18),
    SUICA(180, "SUI", "Suiça", Continent.EUROPE, 18),
    SURINAME(181, "SUR", "Suriname", Continent.NORTH_AMERICA, 13),
    TADJQUISTAO(182, "TAD", "Tadjquistão", Continent.ASIA, 14),
    TAILANDIA(183, "TAI", "Tailândia", Continent.ASIA, 14),
    TAITI(184, "TTI", "Taiti", Continent.OCEANIA, 14),
    TAIPE_CHINES(185, "TAW", "Taipé Chinês", Continent.ASIA, 13),
    TANZANIA(186, "TAN", "Tânzania", Continent.AFRICA, 13),
    TOGO(187, "TGO", "Togo", Continent.AFRICA, 14),
    TONGA(188, "TON", "Tonga", Continent.OCEANIA, 12),
    TRINIDAD_E_TOBAGO(189, "TRT", "Trinidad e Tobago", Continent.NORTH_AMERICA, 15),
    TUNISIA(190, "TUN", "Tunísia", Continent.AFRICA, 17),
    TURCOMENISTAO(191, "TCM", "Turcomenistão", Continent.ASIA, 14),
    TURQUIA(192, "TUR", "Turquia", Continent.EUROPE, 18),
    UCRANIA(193, "UCR", "Ucrânia", Continent.EUROPE, 17),
    UGANDA(194, "UGA", "Uganda", Continent.AFRICA, 15),
    URUGUAI(195, "URU", "Uruguai", Continent.SOUTH_AMERICA, 19),
    UZBEQUISTAO(196, "UZB", "Uzbequistão", Continent.ASIA, 15),
    VANUATU(197, "VAN", "Vanuatu", Continent.OCEANIA, 13),
    VENEZUELA(198, "VEN", "Venezuela", Continent.SOUTH_AMERICA, 16),
    VIETNA(199, "VIE", "Vietnã", Continent.ASIA, 15),
    ZAMBIA(200, "ZAM", "Zâmbia", Continent.AFRICA, 15),
    ZIMBABUE(201, "ZIM", "Zimbabue", Continent.AFRICA, 14),
    COMORES(202, "ICM", "Comores", Continent.AFRICA, 12),
    MICRONESIA(203, "MIC", "Micronésia", Continent.OCEANIA, 13),
    ILHAS_MARSHALL(204, "IMA", "Ilhas Marshall", null, 12),
    MAURICIA(205, "IMR", "Maurícia", Continent.AFRICA, 12),
    NAURU(206, "NAU", "Nauru", Continent.OCEANIA, 13),
    PALAU(207, "PLU", "Palau", null, 12),
    KIRIBATI(208, "KIR", "Kiribati", Continent.OCEANIA, 13),
    SUDAO_DO_SUL(209, "SUS", "Sudão do Sul", Continent.AFRICA, 13),
    TUVALU(210, "TUV", "Tuvalu", Continent.OCEANIA, 13),
    ILHAS_VIRGENS_AMERICANAS(211, "IVA", "Ilhas Virgens Americanas", Continent.NORTH_AMERICA, 12),
    MONTSERRAT(212, "MST", "Montserrat", Continent.NORTH_AMERICA, 13),
    ILHAS_TURKS_E_CAICOS(213, "ITC", "Ilhas Turks e Caicos", Continent.NORTH_AMERICA, 12),
    SAMOA_AMERICANA(214, "SME", "Samoa Americana", Continent.OCEANIA, 12),
    NOVA_CALEDONIA(215, "NCA", "Nova Caledônia", Continent.OCEANIA, 13),
    GIBRALTAR(216, "GIB", "Gibraltar", Continent.EUROPE, 13),
    GUADALUPE(217, "GDA", "Guadalupe", Continent.NORTH_AMERICA, 13),
    GUAM(218, "GMA", "Guam", Continent.ASIA, 12),
    MARTINICA(219, "MTI", "Martinica", Continent.NORTH_AMERICA, 13),
    GUIANA_FRANCESA(220, "GFR", "Guiana Francesa", Continent.NORTH_AMERICA, 13),
    BONAIRE(221, "BON", "Bonaire", Continent.NORTH_AMERICA, 11),
    SAO_MARTINHO_FRANCES(222, "SMF", "São Martinho Francês", Continent.NORTH_AMERICA, 11),
    SAO_MARTINHO_HOLANDES(223, "SMH", "São Martinho Holandês", Continent.NORTH_AMERICA, 11);

    private final int id;
    private final String code;
    private final String name;
    private final Continent continent;
    private final int level;

    Country(int id, String code, String name, Continent continent, int level) {
        this.id = id;
        this.code = code;
        this.name = name;
        this.continent = continent;
        this.level = level;
    }

    public int getId() { return id; }
    public String getCode() { return code; }
    public String getName() { return name; }
    public Continent getContinent() { return continent; }
    public int getLevel() { return level; }

    public static Country fromId(int id) {
        for (Country c : values()) {
            if (c.id == id) return c;
        }
        return null;
    }
}
