logging.level.root=ERROR
logging.level.br.com.saveeditor=WARN
logging.level.br.com.saveeditor.brasfoot=DEBUG
logging.level.org.hibernate=ERROR
logging.file.path=logs
spring.main.banner-mode=console
spring.main.web-application-type=none
spring.main.log-startup-info=false
